### ISSUE TITLE
Support for Jest 27 

### ISSUE THREAD

**Issue by tahme** [CaffeinatedCM/chai-jest-mocks#13]
Tests using the library currently fail when using Jest 27.

Example output with `chai.expect(mockFn).to.have.beenCalled();`
```
jestMock.isMockFunction is not a function

TypeError: jestMock.isMockFunction is not a function
    at ensureMock (https://738by.csb.app/node_modules/chai-jest-mocks/lib/utils/ensureMock.js:15:17)
    at Proxy.eval (https://738by.csb.app/node_modules/chai-jest-mocks/lib/matchers/beenCalled.js:13:7)
    ...
```

Sandbox here: https://codesandbox.io/s/nostalgic-hermann-738by?file=/jest.test.js

**Comment by rzbasereh** [comment]
I have same error!!!!
