### ISSUE TITLE
Fails with `automock: true`

### ISSUE THREAD

**Issue by leegee** [CaffeinatedCM/chai-jest-mocks#2]
When my Jest config turns on automocking:
```
  ● Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at Function.keys (<anonymous>)

       7 |
       8 | chai.use(require('chai-dom'));
    >  9 | chai.use(require('chai-jest-mocks'));
         |          ^
      10 | chai.use(require('chai-jest-snapshot'));
      11 | chai.use(require('chai-jest-diff').default());
      12 |

      at node_modules/color-convert/index.js:68:27
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/color-convert/index.js:61:8)
      at Object.<anonymous> (node_modules/chai-jest-mocks/lib/matchers/beenCalled.js:3:5)
      at Object.<anonymous> (node_modules/chai-jest-mocks/lib/matchers/index.js:3:15)
      at Object.<anonymous> (node_modules/chai-jest-mocks/lib/index.js:1:45)
      at Object.require (test/lib/setup-jest-after-env.js:9:10)
          at Array.forEach (<anonymous>)
```

Latest version of this lib, on latest OSX:
```
Lees-MacBook-Pro:app lee$ jest -v
24.8.0
Lees-MacBook-Pro:app lee$ node -v
v10.16.0
Lees-MacBook-Pro:app lee$ npm -v
6.9.2
Lees-MacBook-Pro:app lee$
```

**Comment by CaffeinatedCM** [comment]
Thanks for reporting this! I was able to reproduce it on my machine, and I could also reproduce it for the `chai-jest-diff` library. Interestingly the error comes from a requirement in the `jest-matcher-utils` that both this library and `chai-jest-diff` use. I'm going to keep investigating this and log an issue with jest

**Comment by CaffeinatedCM** [comment]
I also just tried running chai alone with automock on and it fails: 

```js
const chai = require('chai');
const expect = chai.expect;

describe('add', () => {
  it('does the thing', () => {
    expect(1+2).to.equal(3);
  })
});
```
`TypeError: expect is not a function`


Since these modules are used for assertions, it's probably best to not have them mocked. You can use `jest.dontMock('chai').dontMock('chai-jest-mocks')` to tell jest to never mock them. For example:

```js
jest.dontMock('chai').dontMock('chai-jest-mocks');

const chai = require('chai');

chai.use(require('chai-jest-mocks'));

const {expect} = chai;

describe('add', () => {
  it('does the thing', () => {
    expect(1+2).to.equal(3);
  })

  it('mockfn', () => {
    const fn = jest.fn();
    expect(fn).not.to.have.beenCalled();
  })
});
```
